// src/context/actionTypes.js
console.log('Инициализация типов действий');

const ActionTypes = {
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  SET_ACTIVE_CONTEXT_BLOCK: 'SET_ACTIVE_CONTEXT_BLOCK',
  SET_ACTIVE_PROMPT_BLOCK: 'SET_ACTIVE_PROMPT_BLOCK',
  
  UPDATE_CONTEXT_BLOCK: 'UPDATE_CONTEXT_BLOCK',
  UPDATE_CONTEXT_ITEM: 'UPDATE_CONTEXT_ITEM',
  ADD_CONTEXT_BLOCK: 'ADD_CONTEXT_BLOCK',
  ADD_CONTEXT_ITEM: 'ADD_CONTEXT_ITEM',
  DELETE_CONTEXT_BLOCK: 'DELETE_CONTEXT_BLOCK',
  DELETE_CONTEXT_ITEM: 'DELETE_CONTEXT_ITEM',
  
  // Новый тип действия для добавления нескольких элементов сразу
  ADD_MULTIPLE_CONTEXT_ITEMS: 'ADD_MULTIPLE_CONTEXT_ITEMS',
  
  // Типы действий для работы с подэлементами контекста
  ADD_CONTEXT_SUBITEM: 'ADD_CONTEXT_SUBITEM',
  UPDATE_CONTEXT_SUBITEM: 'UPDATE_CONTEXT_SUBITEM',
  DELETE_CONTEXT_SUBITEM: 'DELETE_CONTEXT_SUBITEM',
  MOVE_CONTEXT_SUBITEM_UP: 'MOVE_CONTEXT_SUBITEM_UP',
  MOVE_CONTEXT_SUBITEM_DOWN: 'MOVE_CONTEXT_SUBITEM_DOWN',
  
  UPDATE_PROMPT_BLOCK: 'UPDATE_PROMPT_BLOCK',
  ADD_PROMPT_BLOCK: 'ADD_PROMPT_BLOCK',
  DELETE_PROMPT_BLOCK: 'DELETE_PROMPT_BLOCK',
  UPDATE_SELECTED_CONTEXTS: 'UPDATE_SELECTED_CONTEXTS',
  
  MOVE_CONTEXT_BLOCK_UP: 'MOVE_CONTEXT_BLOCK_UP',
  MOVE_CONTEXT_BLOCK_DOWN: 'MOVE_CONTEXT_BLOCK_DOWN',
  MOVE_PROMPT_BLOCK_UP: 'MOVE_PROMPT_BLOCK_UP',
  MOVE_PROMPT_BLOCK_DOWN: 'MOVE_PROMPT_BLOCK_DOWN',
  
  MOVE_CONTEXT_ITEM_UP: 'MOVE_CONTEXT_ITEM_UP',
  MOVE_CONTEXT_ITEM_DOWN: 'MOVE_CONTEXT_ITEM_DOWN',
  
  CREATE_NEW_PROJECT: 'CREATE_NEW_PROJECT',
  LOAD_PROJECT: 'LOAD_PROJECT',
  SET_PROJECT_NAME: 'SET_PROJECT_NAME',
  SET_PROJECT_PATH: 'SET_PROJECT_PATH',
  
  CREATE_NEW_TEMPLATE: 'CREATE_NEW_TEMPLATE',
  OPEN_TEMPLATE: 'OPEN_TEMPLATE',
  SAVE_TEMPLATE: 'SAVE_TEMPLATE',
  SAVE_TEMPLATE_AS: 'SAVE_TEMPLATE_AS',
  SET_TEMPLATE_NAME: 'SET_TEMPLATE_NAME',
  SET_TEMPLATE_FILENAME: 'SET_TEMPLATE_FILENAME',
  LOAD_PROJECT_TEMPLATE: 'LOAD_PROJECT_TEMPLATE',
  
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
  
  EXPORT_CONTEXT_BLOCK: 'EXPORT_CONTEXT_BLOCK',
  IMPORT_CONTEXT_BLOCK: 'IMPORT_CONTEXT_BLOCK',

  // Действия для установки различных директорий
  SET_TEMPLATE_FOLDER: 'SET_TEMPLATE_FOLDER',       // Для .txt шаблонов промптов
  SET_PROJECT_FOLDER: 'SET_PROJECT_FOLDER',         // Для проектов
  SET_PROJECT_TEMPLATE_FOLDER: 'SET_PROJECT_TEMPLATE_FOLDER', // Для шаблонов проектов
  SET_CONTEXT_DATA_FOLDER: 'SET_CONTEXT_DATA_FOLDER', // Для блоков контекста
  
  // AI интеграция
  SET_AI_PROVIDER_KEY: 'SET_AI_PROVIDER_KEY',
  UPDATE_AI_PROVIDER_STATUS: 'UPDATE_AI_PROVIDER_STATUS',
  SET_AI_PROVIDER_MODELS: 'SET_AI_PROVIDER_MODELS',
  ADD_AI_MODEL_CONFIG: 'ADD_AI_MODEL_CONFIG',
  UPDATE_AI_MODEL_CONFIG: 'UPDATE_AI_MODEL_CONFIG',
  REMOVE_AI_MODEL_CONFIG: 'REMOVE_AI_MODEL_CONFIG',
  SET_CURRENT_AI_MODEL: 'SET_CURRENT_AI_MODEL',
  UPDATE_AI_GLOBAL_SETTINGS: 'UPDATE_AI_GLOBAL_SETTINGS',
  CHECK_AI_PROVIDERS_STATUS: 'CHECK_AI_PROVIDERS_STATUS',
  SET_AVAILABLE_MODELS: 'SET_AVAILABLE_MODELS',
  LOAD_AI_CONFIG: 'LOAD_AI_CONFIG'
};

export default ActionTypes;